import { type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { ClassDiagramGeneratedModule, ClassDiagramGeneratedSharedModule } from './generated/module.js';
import { ClassDiagramValidator, registerValidationChecks } from './class-diagram-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type ClassDiagramAddedServices = {
    validation: {
        ClassDiagramValidator: ClassDiagramValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type ClassDiagramServices = LangiumServices & ClassDiagramAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const ClassDiagramModule: Module<ClassDiagramServices, PartialLangiumServices & ClassDiagramAddedServices> = {
    validation: {
        ClassDiagramValidator: () => new ClassDiagramValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createClassDiagramServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    ClassDiagram: ClassDiagramServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        ClassDiagramGeneratedSharedModule
    );
    const ClassDiagram = inject(
        createDefaultModule({ shared }),
        ClassDiagramGeneratedModule,
        ClassDiagramModule
    );
    shared.ServiceRegistry.register(ClassDiagram);
    registerValidationChecks(ClassDiagram);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, ClassDiagram };
}
